language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  # command to run tests
# use PostgreSQL https://docs.travis-ci.com/user/database-setup/#postgresql
services:
  - postgresql
# set up project-specific database and user (with CREATEDB privilege so that
# it may create test databases)
before_script:
  - psql -c 'CREATE DATABASE projectdb;' -U postgres
  - psql -c "CREATE ROLE travis_user PASSWORD 'dbpassword' NOSUPERUSER CREATEDB LOGIN;" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE projectdb TO travis_user;' -U postgres
script:
  - export $(grep -v '^#' .env.travis | xargs)
  - python3.9 manage.py makemigrations
  - python3.9 manage.py migrate
  - python3.9 manage.py test
