# Generated by Django 3.2.2 on 2021-05-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_start_datetime', models.DateTimeField()),
                ('last_forecast_update_datetime', models.DateTimeField()),
                ('new_req_allowed_datetime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('symbol_name_0h', models.CharField(max_length=50)),
                ('t_0h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_1h', models.CharField(max_length=50)),
                ('t_1h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_2h', models.CharField(max_length=50)),
                ('t_2h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_3h', models.CharField(max_length=50)),
                ('t_3h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_4h', models.CharField(max_length=50)),
                ('t_4h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_5h', models.CharField(max_length=50)),
                ('t_5h', models.DecimalField(decimal_places=1, max_digits=4)),
                ('symbol_name_6h', models.CharField(max_length=50)),
                ('t_6h', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
