# Generated by Django 3.2.2 on 2021-05-12 07:47
from datetime import datetime, timezone

from django.db import migrations

def add_forecastpoints(app_registry, schema_editor):
    ForecastPoint = app_registry.get_model('weather', 'ForecastPoint')
    new_points = [
        {
            'latitude': -59.3103,
            'longitude': -14.4888,
            'forecast_start_datetime': datetime(2002, 3, 2, 0, 0, 0, 0, tzinfo=timezone.utc),
            'last_forecast_update_datetime': datetime(2002, 3, 2, 9, 54, 5, 20*1000, tzinfo=timezone.utc),
            'new_req_allowed_datetime': datetime(2002, 3, 2, 10, 30, 2, 40*1000, tzinfo=timezone.utc),
            'symbol_name_0h': 'clearsky_night',
            't_0h': 20.1,
            'symbol_name_1h': 'cloudy',
            't_1h': 18.5,
            'symbol_name_2h': 'fair_day',
            't_2h': 17.2,
            'symbol_name_3h': 'fog',
            't_3h': 16.0,
            'symbol_name_4h': 'heavyrainshowersandthunder_day',
            't_4h': 14.8,
            'symbol_name_5h': 'heavysleetshowersandthunder_polartwilight',
            't_5h': 13.2,            
            'symbol_name_6h': 'clearsky_polartwilight',
            't_6h': 11.0,
        },
        {
            'latitude': -5.8100,
            'longitude': -3.0000,
            'forecast_start_datetime': datetime(2021, 5, 10, 0, 0, 0, 0, tzinfo=timezone.utc),
            'last_forecast_update_datetime': datetime(2021, 5, 9, 23, 20, 8, 0, tzinfo=timezone.utc),
            'new_req_allowed_datetime': datetime(2021, 5, 10, 0, 35, 0, 0, tzinfo=timezone.utc),
            'symbol_name_0h': 'snow',
            't_0h': -3.0,
            'symbol_name_1h': 'snowandthunder',
            't_1h': -5.7,
            'symbol_name_2h': 'snowshowers_day',
            't_2h': -4.1,
            'symbol_name_3h': 'snowshowersandthunder_night',
            't_3h': -8.2,
            'symbol_name_4h': 'heavyrainshowersandthunder_day',
            't_4h': -10.5,
            'symbol_name_5h': 'heavysleetshowersandthunder_polartwilight',
            't_5h': -5.8,            
            'symbol_name_6h': 'clearsky_polartwilight',
            't_6h': 3.5,
        },
    ]
    for p in new_points:
        ForecastPoint.objects.create(**p)

class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial')
    ]

    add_funs = (
        add_forecastpoints,
    )

    operations = [migrations.RunPython(add_fun) for add_fun in add_funs]
